import frappe
from frappe import _
from frappe.model.document import Document
from frappe.utils import flt, now


class ShiftPaymentReconciliation(Document):
    def before_submit(self):
        setup = frappe.get_doc(
            "Payment Method Clearing Setup",
            self.setup_reference,
        )

        if not setup.enabled:
            frappe.throw(_("The selected clearing setup is disabled."))

        self.clearing_account = setup.clearing_account
        self.destination_account = setup.destination_account
        self.settlement_policy = setup.settlement_policy
        self.fee_account = setup.fee_account

        self.difference = flt(self.reviewed_amount) - flt(self.expected_amount)
        self.net_transfer_amount = flt(self.reviewed_amount) - flt(self.fee_amount)

        if flt(self.reviewed_amount) <= 0:
            frappe.throw(_("Reviewed Amount must be greater than zero."))

        if abs(flt(self.difference)) > 0.01:
            frappe.throw(_("Reviewed Amount must equal Expected Amount."))

        if flt(self.net_transfer_amount) < 0:
            frappe.throw(_("Fee Amount cannot exceed Reviewed Amount."))

        if flt(self.fee_amount) > 0 and not self.fee_account:
            frappe.throw(_("Fee Account is required."))

        self.status = "Reviewed"
        self.reviewed_by = frappe.session.user
        self.reviewed_at = now()

    def on_submit(self):
        # Review confirmation only. The Journal Entry is generated by the
        # final Pharmacy Shift approval flow.
        frappe.db.set_value(
            self.doctype,
            self.name,
            {
                "status": "Reviewed",
                "journal_entry": "",
            },
            update_modified=False,
        )

    def before_cancel(self):
        if not self.journal_entry:
            return

        journal = frappe.get_doc("Journal Entry", self.journal_entry)
        if journal.docstatus == 1:
            journal.flags.ignore_permissions = True
            journal.cancel()
